server:
  port: 7090
  servlet:
    context-path: /api
spring:
  application:
    name: kunpan
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
      username: root
      password:
  mail:
    username: 2472503964@qq.com
    port: 465
    password: cgsptxagxktmdjbc
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  rabbitmq:
    host: 101.126.93.113
    port: 5672
    virtual-host: /vagrant
    username: vagrant
    password: vagrant
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        multiplier: 2
      mandatory: true
    publisher-confirm-type: none
    publisher-returns: false
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
mybatis-plus:
  type-aliases-package: com.example